backend:
  name: git-gateway
  branch: main  # 如果你的 GitHub 仓库主分支是 master，请改成 master

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "chapters"
    label: "章节"
    folder: "chapters"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "摘录", name: "quote", widget: "text", required: false }
      - { label: "正文", name: "body", widget: "markdown" }
      - { label: "插图", name: "image", widget: "image", required: false }